project_id = "xshop"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = [
  "http://localhost:5173/auth/callback",
  "http://localhost:5173/reset-password"
]

[auth.email]
enable_signup = true
enable_confirmations = true
double_confirm_changes = true
